### ISSUE TITLE
what's causing a lot of chain calls on light nodes

### ISSUE THREAD

**Issue by acud** [ethersphere/bee-backlog#19]

**Comment by aloknerurkar** [comment]
So I did not find anything while running in testnet. Is this seen on mainnet?

**Comment by mrekucci** [comment]
The claim was not confirmed, the following are the results from performed tests:

Testnet after synced blockchain:
![testnet.png](https://images.zenhubusercontent.com/606c596b9330691dfdef51ad/a5ef82b1-987e-45ef-9215-336defa06bcf)

Mainnet fresh after db nuke:
![db_nuke.png](https://images.zenhubusercontent.com/606c596b9330691dfdef51ad/beaeb604-1af1-46bf-b5b4-ed75ac016690)

Mainnet after synced blockchain:
![normal.png](https://images.zenhubusercontent.com/606c596b9330691dfdef51ad/c25fe642-0829-45ec-9169-5c8b495313c1)

**Comment by mrekucci** [comment]
With postage snapshot enabled:
![postage-snapshot.png](https://images.zenhubusercontent.com/606c596b9330691dfdef51ad/5f44ac5b-2a98-4ee8-b0af-b41621ddbea8)

**Comment by agazso** [comment]
As per our discussion on the meeting, it would be good to be able to tell more specifically what kind of requests causes the big spike in the call at the beginning, in order to be understand how we can mitigate it, especially in the case of the light node / desktop app.

For example if it is caused be the overlay verification then this may be problematic, because then the number of initial requests depend on the number of peers of the node, which in turn is a function of the size of the network that we are not able to control. So once the app becomes popular the spike may become even bigger and at some point it may go over the rate limit of the RPC endpoint.

**Comment by mrekucci** [comment]
The big spike investigation results:
![spike.png](https://images.zenhubusercontent.com/606c596b9330691dfdef51ad/ee809192-29cf-4871-ac61-41f3d7d91a0a)

The following is the breakdown (at the bee component level) of the chain calls from the chart above:
```
TransactionReceipt:
	+-> transaction.WaitBlockAfterTransaction 1
	+-> transaction.Matches                   193
TransactionByHash:
	+-> transaction.Matches                   193
ChainID:
	+-> node.InitChain                        1
BlockNumber:
	+-> transaction.WaitBlockAfterTransaction 1
	+-> listener.Listen                       1156
	+-> chainsyncer.getBlockHeight            9
	+-> transaction.IsSynced                  1
FilterLogs:
	+-> listener.Listen                       1155
HeaderByNumber:
	+-> transaction.IsSynced                  1
	+-> transaction.WaitBlockAfterTransaction 1
	+-> transaction.Matches                   186
	+-> chainsyncer.getBlockHeight            2
	+-> chainsync.syncHandler                 2
CodeAt:
	+-> chequebook.VerifyBytecode             2
CallContract:
	+-> transaction.Call                      6
```

**Comment by agazso** [comment]
Thanks for investigating!

To sum up, the big spike seems to come from the initial postage stamp syncing, which can be mitigated by using the postage snapshot feature, assuming there are recent snapshots made.
